// <auto-generated />
using Meus_Produtos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Meus_Produtos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210715194422_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("Meus_Produtos.Data.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Caderno",
                            Preco = 7.95m,
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Perfume",
                            Preco = 125.00m,
                            Status = "Inativo"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Camiseta",
                            Preco = 24.99m,
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Cadeira",
                            Preco = 45.99m,
                            Status = "Inativo"
                        });
                });

            modelBuilder.Entity("Meus_Produtos.Data.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "brenda@gmail.com",
                            Nome = "Brenda",
                            Senha = "123456abc"
                        },
                        new
                        {
                            Id = 2,
                            Email = "jose@gmail.com",
                            Nome = "José",
                            Senha = "986324lsk"
                        },
                        new
                        {
                            Id = 3,
                            Email = "marcos@gmail.com",
                            Nome = "Marcos",
                            Senha = "147852pod"
                        },
                        new
                        {
                            Id = 4,
                            Email = "fabiana@gmail.com",
                            Nome = "Fabiana",
                            Senha = "369825lei"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
